spring:
  config:
    activate:
      on-profile: local
    import:
      - "classpath:/application-prod-db.yml"
      - "classpath:/application-secret.yml"
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
